class ErrorMessages:
    MEMBER_NOT_FOUND = "Member not found"
    BOOK_NOT_FOUND = "Book not found"
    INVALID_TOKEN="Invalid Token"
    MAGAZINE_NOT_FOUND = "Magazine not found"
    PUBLISHER_NOT_FOUND = "Publisher not found"
    CATEGORY_NOT_FOUND = "Category not found"
    INVALID_CREDENTIALS = "Invalid credentials"
    BOOK_ALREADY_BORROWED = "Book is already borrowed"
    MAGAZINE_ALREADY_BORROWED = "Magazine is already borrowed"
    BOOK_ALREADY_RETURNED = "Book already returned"
    MAGAZINE_ALREADY_RETURNED = "Magazine already returned"
    MAGAZINE_NOT_FOUND="Magazine not found !"
    FAILED_TO_BORROW_MAGAZINE = "Failed to borrow Magazine"
    MAGAZINE_AND_MEMBER_NOT_FOUND = "Magazine and member not found"
    BOOK_OR_MEMBER_NOT_FOUND = "Book or member not found"
    CREDENTIALS_NOT_MATCHED = "Book and Member credentials not matched"
    BOOK_OR_MEMBER_NOT_FOUND="Book or member not found"
    DUPLICATE_ISBN = "Duplicate ISBN: Failed to add magazine"
    INVALID_EMAIL="Invalid email ,Please provide a valid email !"
    ALL_FIELD_REQUIRED="All field required !"
    ALREADY_EXIST_EMAIL="Member with this email already exists !"
    MEMBER_ADDED="Member added Successfully !"
    BOOK_ADDED="Book added Successfully !"
    BOOK_ALREADY_EXIT_OF_ISBN="Book is already exist with isbn numnber !"
    RECORD_ADDED="Record add sucessfully !"
    PROVIDE_BOOK_MEMBER="provide both book and member"
    PROVIDE_MAGAZINE_MEMBER="provide both book and member"
    UPDATE_RETURN_BOOK="Update returned book sucessfully !"
    UPDATE_RETURN_MAGAZINE="Update returned book sucessfully !"
    MAGAZINE_ALREADY_EXIST="Magazine already exists"
    MAGAZINE_ADDED="Magazine added Successfully !"
    PUBLISHER_ADDED="Magazine added Successfully !"
    ALREADY_EXIST_PUBLISHER="Already exist publisher !"
    CATEGORY_ADDED="Category already exists"
    CATEGORY_EXIST="Category already exists"
    BOOK_MAGAZINE_NOT_FOUND="No book and Magazine Found !"
    
    

    